/*===========================================================================
    FName C++ declarations exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2012 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if !ENUMS_ONLY
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#if !defined(__EXAMPLEGAME_NAMES_H__) || defined(NAMES_ONLY)

#ifndef __EXAMPLEGAME_NAMES_H__
#define __EXAMPLEGAME_NAMES_H__
#endif

#ifndef AUTOGENERATE_NAME
#define DEFINED_NAME_MACRO
#define AUTOGENERATE_NAME(name) extern FName EXAMPLEGAME_##name;
#endif


AUTOGENERATE_NAME(ProcCtrlMsg)
AUTOGENERATE_NAME(ProcFireMsg)

#ifdef DEFINED_NAME_MACRO
#undef DEFINED_NAME_MACRO
#undef AUTOGENERATE_NAME
#endif

#endif	//HEADER_GUARD

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#endif	//	!ENUMS_ONLY

